set_global_assignment -name VERILOG_FILE modules/top/top.v
set_global_assignment -name VERILOG_FILE modules/fx3/fx3.v
set_global_assignment -name VERILOG_FILE modules/pll/pll.v
set_global_assignment -name VERILOG_FILE modules/id/id.v
set_global_assignment -name VERILOG_FILE modules/pwr/pwr.v
set_global_assignment -name VERILOG_FILE modules/adc/adc.v
set_global_assignment -name VERILOG_FILE modules/ctrl/ctrl.v
set_global_assignment -name VERILOG_FILE modules/ctrl/ctrl_arb.v
set_global_assignment -name VERILOG_FILE modules/ctrl/ctrl_soft.v
set_global_assignment -name VERILOG_FILE modules/ip/fifo.v
set_global_assignment -name VERILOG_FILE modules/flash/synthesis/flash.v
set_global_assignment -name VERILOG_FILE modules/flash/synthesis/submodules/altera_serial_flash_loader.v
set_global_assignment -name VERILOG_FILE modules/trg/trg.v
set_global_assignment -name VERILOG_FILE modules/trg/trg_cond.v
set_global_assignment -name VERILOG_FILE modules/trg/trg_edge.v
set_global_assignment -name VERILOG_FILE modules/trg/trg_mon.v
set_global_assignment -name VERILOG_FILE modules/trg/trg_seq.v
set_global_assignment -name VERILOG_FILE modules/alpideio/alpideio.v
set_global_assignment -name VERILOG_FILE modules/alpiderst/alpiderst.v
set_global_assignment -name VERILOG_FILE modules/rdo/rdo.v
set_global_assignment -name VERILOG_FILE modules/rdo/rdo_mux.v
set_global_assignment -name VERILOG_FILE modules/evt/xonxoff.v
set_global_assignment -name VERILOG_FILE modules/evt/evt_packer.v
set_global_assignment -name VERILOG_FILE modules/evt/evt_builder.v
set_global_assignment -name VERILOG_FILE modules/evt/evt_fifo.v
set_global_assignment -name VERILOG_FILE modules/evt/data_fifo.v
set_global_assignment -name VERILOG_FILE modules/rdoctrl/rdoctrl.v
set_global_assignment -name VERILOG_FILE modules/rdoctrl/rdoctrl_decoder.v
set_global_assignment -name VERILOG_FILE modules/ip/syncin.v
set_global_assignment -name VERILOG_FILE modules/ip/noglitch.v
set_global_assignment -name VERILOG_FILE modules/bus/bus.v
set_global_assignment -name VERILOG_FILE modules/bus/bus_fifo_in.v
set_global_assignment -name VERILOG_FILE modules/bus/bus_fifo_out.v
set_global_assignment -name VERILOG_FILE modules/tsys/tsys.v
